title: Tutorial
author: UR BOI
email: no u
description: > # this means to ignore newlines until "baseurl:"
1337 h4x0r

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
